Employee/Employee.Web/Models/ErrorViewModel.cs
using System;

namespace Employee.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Employee/Employee.Web/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Employee.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Employee.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeDataService employeeDataService;
        private readonly ILocationService locationService;
        public EmployeeController(IEmployeeDataService employeeDataService, ILocationService locationService)
        {
            this.employeeDataService = employeeDataService;
            this.locationService = locationService;
        }
        // GET: EmployeeController
        public ActionResult Index()
        {
            var cities = locationService.GetAllCities().ToDictionary(x => x.Id + "_" + x.StateId, y => y.Name);
            var states = locationService.GetAllStates().ToDictionary(x => x.Id, y => y.Name);
            var employess = employeeDataService.GetAll().Select(x =>
            {
                x.State = states.ContainsKey(x.StateId) ? states[x.StateId] : string.Empty;
                x.City = cities.ContainsKey(x.CityId + "_" + x.StateId) ? cities[x.CityId + "_" + x.StateId] : string.Empty;

                return x;
            }).ToList();
            return View(employess);
        }

        // GET: EmployeeController/Details/5
        public List<Employee.Model.City> Cities(int id)
        {
            return locationService.GetAllCities().Where(x=>x.StateId==id).ToList();
        }

        // GET: EmployeeController/Create
        public ActionResult Create()
        {
            ViewBag.States = locationService.GetAllStates(null);
            ViewBag.Cities = locationService.GetCitiesByState(null);
            return View();
        }

        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Employee.Model.Employee employee)
        {
            try
            {

                employeeDataService.Add(employee);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.States = locationService.GetAllStates(null);
                ViewBag.Cities = locationService.GetAllStates(null);
                return View();
            }
        }

        // GET: EmployeeController/Edit/5
        public ActionResult Edit(int id)
        {

            var employee = employeeDataService.GetAll().FirstOrDefault(x => x.Id == id);
            ViewBag.States = locationService.GetAllStates(employee.StateId);
            ViewBag.Cities = locationService.GetCitiesByState(employee.StateId, employee.CityId);
            return PartialView(employee);
        }

        // POST: EmployeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Model.Employee employee)
        {
            try
            {
                employee.Id = id;
                employeeDataService.Update(employee);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: EmployeeController/Delete/5
        public bool Delete(int id)
        {
            employeeDataService.Remove(id);
            return true;
        }


    }
}

Employee/Employee.Web/Controllers/GitHubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Employee.Web.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Employee.Web.Controllers
{
    public class GitHubController : Controller
    {
        // GET: GitHubController
        private readonly IGitHubDataService gitHubDataService;
        public GitHubController(IGitHubDataService gitHubDataService)
        {
            this.gitHubDataService = gitHubDataService;
        }
        public async Task<ActionResult> Index()
        {
            var result = await gitHubDataService.GetGitHubRepos();
            return View(result);
        }


    }
}

Employee/Employee.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Employee.Web.Models;

namespace Employee.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Employee/Employee.Web/Views/Employee/Create.cshtml
@model Employee.Model.Employee

@{
    ViewData["Title"] = "Create";
}

<h4>Create Employee</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FirstName" class="control-label"> First Name :</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last Name :</label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StateId" class="control-label">State :</label>
                @Html.DropDownListFor(m => m.StateId, (List<SelectListItem>)ViewBag.States, "Please select State", new { @class = "form-control" })
                <span asp-validation-for="StateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CityId" class="control-label">City :</label>
                @Html.DropDownListFor(m => m.CityId,(List<SelectListItem>) ViewBag.Cities, "Please select City", new { @class="form-control"})
                <span asp-validation-for="CityId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Gender" class="control-label">Gender :</label>
                <input type="radio" name="Gender" value="Male"  /> Male
                <input type="radio" name="Gender" value="Female"  /> Female
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Employee/Employee.Web/Views/Employee/Edit.cshtml
@model Employee.Model.Employee
@{
    Layout = "";
}
<div class="modal fade" id="editEmployeeModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">Edit Employee</div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <form asp-action="Edit">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                            <div class="form-group">
                                <label asp-for="FirstName" class="control-label"> First Name :</label>
                                <input asp-for="FirstName" class="form-control" />
                                <span asp-validation-for="FirstName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="LastName" class="control-label">Last Name :</label>
                                <input asp-for="LastName" class="form-control" />
                                <span asp-validation-for="LastName" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StateId" class="control-label">State :</label>
                                @Html.DropDownListFor(m => m.StateId, (List<SelectListItem>)ViewBag.States, "Please select State", new { @class = "form-control" })
                                <span asp-validation-for="StateId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CityId" class="control-label">City :</label>
                                @Html.DropDownListFor(m => m.CityId, (List<SelectListItem>)ViewBag.Cities, "Please select City", new { @class = "form-control"  })
                                <span asp-validation-for="CityId" class="text-danger"></span>
                            </div>

                            <div class="form-group">
                                <label asp-for="Gender" class="control-label">Gender :</label>
                                <input type="radio" name="Gender" value="Male" checked='@(Model.Gender == "Male")' /> Male
                                <input type="radio" name="Gender" value="Female" checked='@(Model.Gender == "Female")' /> Female
                                <span asp-validation-for="Gender" class="text-danger"></span>
                            </div>
                            <div class="form-group ">
                                <div class="row">
                                    <div class="col-8"></div><div class="col-4">
                                        <input type="submit" value="Save" class="btn btn-primary" />
                                        <input type="button" value="Close" class="btn btn-secondary" data-dismiss="modal" />
                                    </div>
                                </div>

                            </div>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>



Employee/Employee.Web/Views/Employee/Index.cshtml

@model IEnumerable<Employee.Model.Employee>
@{
    ViewBag.Title = "Index";
}

<h4>All Employees</h4>
<div class="row">
    <div class="col-10"></div>
    <div class="col-2"> @Html.ActionLink("Add Employee", "Create", "Employee", routeValues: null, htmlAttributes: new { @class = "btn btn-primary", @role = "button" })</div>

</div>

<div class="row">&nbsp;</div>
@if (Model != null)
{
    <table class="table table-bordered table-hover">
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>State</th>
            <th>City</th>
            <th>Gender</th>
            <th colspan="2">Actions</th>
        </tr>
        @foreach (var d in Model)
        {
            <tr>
                <td>@d.FirstName</td>
                <td>@d.LastName</td>
                <td>@d.State</td>
                <td>@d.City</td>
                <td>@d.Gender</td>
                <td>
                    <button class="btn btn-primary" onclick="editEmployee(@d.Id)">Edit</button>
                </td>
                <td> <button class="btn btn-primary" onclick="deleteEmployee(@d.Id,'@d.FirstName')">Delete</button></td>
            </tr>
        }

    </table>
}
<br />
<div id="editForm"></div>


Employee/Employee.Web/Views/GitHub/Index.cshtml
@model List<Employee.Web.Services.GitHubItem>

<table class="table">
    <thead>
        <tr>
           
            <th>
               Name
            </th>
            <th>
               Full Name
            </th>
            <th>
               Private
            </th>
          
            <th>
               Description
            </th>
           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
           
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.full_name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item._private)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
           
        </tr>
}
    </tbody>
</table>


Employee/Employee.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Employee/Employee.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="GitHub" asp-action="Index">GitHub Repos</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Employee.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>